obj-$(CONFIG_OPLUS_FINGERPRINT_COMMON) += oplus_fp_common/

### Capacitive fingerprint sensor
obj-$(CONFIG_OPLUS_FINGERPRINT_GOODIX) += goodix_optical_fp/

### Optical fingerprint sensor
obj-$(CONFIG_OPLUS_FINGERPRINT_GOODIX_OPTICAL) += goodix_optical_fp/
obj-$(CONFIG_OPLUS_FINGERPRINT_JIIOV_OPTICAL)   += anc_driver/
### FEATURE MACRO
ccflags-$(CONFIG_OPLUS_FINGERPRINT_NAVIGATION_ENABLE) += -DFP_NAVIGATION_ENABLE
