ifeq ($(BUILTIN), 1)
obj-y += rmnet_core.o
obj-y += rmnet_ctl.o
else
obj-m += rmnet_core.o
obj-m += rmnet_ctl.o
endif
rmnet_core-y := rmnet_config.o rmnet_handlers.o rmnet_descriptor.o \
	rmnet_genl.o rmnet_map_command.o rmnet_map_data.o rmnet_vnd.o\
	qmi_rmnet.o wda_qmi.o dfc_qmi.o dfc_qmap.o
rmnet_ctl-y := rmnet_ctl_client.o rmnet_ctl_ipa.o


